alias git="hub"
alias py3init="echo 'layout python3' > .envrc && direnv allow"
alias py2init="echo 'layout python' > .envrc && direnv allow"
alias corpify="touch .envrc && echo 'export GITHUB_HOST=git.corp.adobe.com' >> .envrc && direnv allow"
alias dc="docker-compose"
alias dm="docker-machine"
alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias chefenv="eval $(chef shell-init zsh)"
alias kittyconfig="nvim ~/.config/kitty/kitty.conf"
