#!/bin/env bash

brew tap caskroom/cask
brew install python
brew install chruby
brew install ruby-install
brew install ag
brew install jq
brew cask install chrome
brew cask install seil
brew cask install karabiner
brew install macvim --override-system-vim
brew cask install slack
brew cask install spotify
brew cask install firefox
brew cask install fluid
brew cask install vagrant
brew cask install virtualbox
brew cask install sequelpro
