#!/bin/bash

# brew install caskroom/cask/brew-cask
# brew install python
# brew install "python3"
brew install ag
brew install jq
brew install direnv
brew install tig
brew install tmux
brew install hub
brew install reattach-to-user-namespace
brew install neovim/neovim/neovim
brew install pyenv pyenv-virtualenv pyenv-virtualenvwrapper
# brew tap homebrew/cask-fonts
# brew cask install font-fira-code
# brew cask install google-chrome
# brew cask install seil
# brew cask install karabiner
# brew cask install slack
# brew cask install spotify
# brew cask install firefox
# brew cask install fluid
# brew cask install vagrant
# brew cask install virtualbox
# brew cask install sequel-pro
# brew cask install dropbox
brew cask install docker
brew cask install neovim
brew cask install atom
# brew cask install gitup
brew install htop
