#!/bin/bash

# brew install caskroom/cask/brew-cask
brew install python
# brew install chruby
# brew install ruby-install
brew install ag
brew install jq
brew install direnv
brew install macvim --override-system-vim
brew install tmux
brew install reattach-to-user-namespace
brew install neovim/neovim/neovim
# brew cask install google-chrome
brew cask install seil
brew cask install karabiner
# brew cask install slack
brew cask install spotify
brew cask install firefox
brew cask install fluid
brew cask install vagrant
brew cask install virtualbox
brew cask install sequel-pro
brew cask install dropbox
