#!/usr/bin/env python3
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("pyversion", help="The pyenv version you want to use.")
parser.add_argument("pyvenv", help="The name of the virtual env to create or use.")
args = parser.parse_args()

with open(".envrc", "w+") as f:
    f.write(f"# -*- mode: sh; -*-\n")
    f.write(f"# (rootdir)/.envrc : direnv configuration file\n")
    f.write(f"# see https://direnv.net/\n")
    f.write(f"pyversion={args.pyversion}\n")
    f.write(f"pyvenv={args.pyvenv}\n")
    f.write("\n")
    f.write(f"use pyenvpython {args.pyversion}\n")
    f.write(f"#Create the virtualenv if not yet done.\n")
    f.write(f"layout virtualenv {args.pyversion} {args.pyvenv}\n")
    f.write(f"#activate it\n")
    f.write(f"layout activate {args.pyvenv}-{args.pyversion}\n")
